def cumulative_sum(input_list):
    output_list = [input_list[0]]
    for i in range(1, len(input_list)):
        output_list.append(output_list[-1] + input_list[i] + 1)

    return output_list


def get_indexes(base_str, substr):
    indexes = []
    while base_str.find(substr) != -1:
        index = base_str.find(substr)
        indexes.append(index)
        base_str = base_str[index+1:]

    return cumulative_sum(indexes)


def get_locations(base_str, substr):
    indexes = get_indexes(base_str, substr)
    return list(map(lambda index: index+1, indexes))


def display_formatted_locations(locations):
    for location in locations:
        print(location, end=" ")


if __name__ == '__main__':
    base_string = "GGGGGAGCCACGGGGAGCCGGGGAGCAAAAAAGGGGAGCCAGGGGGAGCACACGGGGGAGCGGGGAGCGGGGAGCATTATCAATGGGGAGCGGGGAGCGGGGAGCGGGGGAGCACTGACCGGGGAGCTTGGGGAGCCAGTTGGGGAGCGGGGGAGCTGGGGAGCCGGGGAGCGGGGGAGCAATAGGGGAGCATGCGGGGGAGCCGGGGAGCCGAATGGGGAGCGTTGGGGGAGCGGGGAGCCTGGGGAGCACTAGGGGAGCGGGGAGCGGGGAGCGAGGGGAGCGGGGAGCGGGGAGCGTACGGGGAGCGGGGAGCGGGGAGCGGGGAGCACCTTTAGGGGAGCAGGGGAGCTGGCACGGGGGAGCTACCACGGGGGGGGAGCGGGGAGCGGGGGAGCCTACGGGGGAGCGAATAAGGGGAGCTGAACGGGGGAGCGGGGAGCTGGGGAGCGGGGAGCGGGGAGCTGGGGAGCCGGGGAGCGGGGGAGCGGGGAGCGGGGAGCGGGGAGCGGACTAGGGGAGCAGTGAAGAGGGGAGCTGGGGAGCGGGGAGCCGGGGAGCAAGTGGGGAGCCTTCGTGGGGAGCCGGGGGAGCACGATGTAGGGGAGCGGGTGGGGAGCACGGGGAGCGGGGGAGCGAAGGGGAGCGATCTCGGGGAGCCGGGGAGCCGGGGGGAGCGGGGAGCGGGGAGCCAACACAGGGGAGCCGCGGGGAGCGCGCAAGGGGAGCCGGGGGAGCGAGATGGGGGAGCGGGGAGCAGTGTAGGGGAGCCGTCGGGGAGCATCCAAGGGGAGCAGGGGAGCGGGGAGCGGGGAGCGGGGGGGAGCCGGGGGAGCCTACGGGGAGCGCAACACGGGGAGCGGGGGAGCGGGGAGC"
    substring = "GGGGAGCGG"
    locations = get_locations(base_string, substring)
    display_formatted_locations(locations)
